import type { DeviceSpec } from '../types';

/**
 * Every device the set draws.
 *
 * Widths and heights are CSS viewports, not panel resolutions — a Pixel has a
 * 1080px-wide panel but lays out at 412 CSS pixels, and previewing at 1080
 * would show a tablet layout on a phone. Bezel, overhang and the chrome
 * measurements mirror the stylesheet, since `frameSize()` measures against them.
 *
 * Sizes are deliberately a little smaller than the real hardware where the real
 * figure would dominate a preview pane; the layout breakpoint each one lands in
 * is what matters, not millimetre fidelity.
 */
export const DEVICES = {
  /* ------------------------------------------------------------- apple -- */

  'macbook-air': {
    id: 'macbook-air',
    label: 'MacBook Air',
    family: 'apple',
    chassis: 'laptop',
    width: 1024,
    height: 640,
    bezel: 9,
    chromeAbove: 14,
    chromeBelow: 14,
    overhang: 26,
    screenRadius: 2,
    chassisRadius: 12,
    camera: 'notch',
    material: 'aluminium',
    speakers: true,
  },

  'macbook-pro-16': {
    id: 'macbook-pro-16',
    label: 'MacBook Pro 16"',
    family: 'apple',
    chassis: 'laptop',
    width: 1152,
    height: 720,
    bezel: 8,
    chromeAbove: 14,
    chromeBelow: 15,
    overhang: 28,
    screenRadius: 2,
    chassisRadius: 14,
    camera: 'notch',
    material: 'graphite',
    speakers: true,
  },

  imac: {
    id: 'imac',
    label: 'iMac',
    family: 'apple',
    chassis: 'monitor',
    width: 1280,
    height: 720,
    bezel: 12,
    chromeAbove: 12,
    chromeBelow: 130,
    overhang: 0,
    screenRadius: 4,
    chassisRadius: 14,
    camera: 'dot',
    material: 'aluminium',
  },

  'ipad-pro': {
    id: 'ipad-pro',
    label: 'iPad Pro',
    family: 'apple',
    chassis: 'tablet',
    width: 1024,
    height: 1366,
    bezel: 10,
    chromeAbove: 14,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 16,
    chassisRadius: 26,
    camera: 'dot',
    cameraBump: true,
  },

  'ipad-air': {
    id: 'ipad-air',
    label: 'iPad Air',
    family: 'apple',
    chassis: 'tablet',
    width: 834,
    height: 1120,
    bezel: 10,
    chromeAbove: 14,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 16,
    chassisRadius: 26,
    camera: 'dot',
  },

  'ipad-mini': {
    id: 'ipad-mini',
    label: 'iPad mini',
    family: 'apple',
    chassis: 'tablet',
    width: 744,
    height: 1024,
    bezel: 9,
    chromeAbove: 12,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 14,
    chassisRadius: 22,
    camera: 'dot',
  },

  'iphone-pro-max': {
    id: 'iphone-pro-max',
    label: 'iPhone Pro Max',
    family: 'apple',
    chassis: 'phone',
    width: 440,
    height: 956,
    bezel: 10,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 50,
    chassisRadius: 60,
    camera: 'island',
    material: 'titanium',
    sideButtons: true,
    homeIndicator: true,
    cameraBump: true,
  },

  'iphone-pro': {
    id: 'iphone-pro',
    label: 'iPhone Pro',
    family: 'apple',
    chassis: 'phone',
    width: 402,
    height: 874,
    bezel: 10,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 46,
    chassisRadius: 56,
    camera: 'island',
    material: 'titanium',
    sideButtons: true,
    homeIndicator: true,
    cameraBump: true,
  },

  iphone: {
    id: 'iphone',
    label: 'iPhone',
    family: 'apple',
    chassis: 'phone',
    width: 393,
    height: 852,
    bezel: 10,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 44,
    chassisRadius: 54,
    camera: 'island',
    sideButtons: true,
    homeIndicator: true,
  },

  'iphone-mini': {
    id: 'iphone-mini',
    label: 'iPhone mini',
    family: 'apple',
    chassis: 'phone',
    width: 375,
    height: 812,
    bezel: 9,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 42,
    chassisRadius: 50,
    camera: 'notch',
    sideButtons: true,
    homeIndicator: true,
  },

  'iphone-se': {
    id: 'iphone-se',
    label: 'iPhone SE',
    family: 'apple',
    chassis: 'phone',
    width: 375,
    height: 667,
    bezel: 10,
    // The forehead and chin either side of the display.
    chromeAbove: 44,
    chromeBelow: 44,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 26,
    camera: 'none',
    sideButtons: true,
  },

  'apple-watch': {
    id: 'apple-watch',
    label: 'Apple Watch',
    family: 'apple',
    chassis: 'watch',
    width: 205,
    height: 251,
    bezel: 12,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 34,
    chassisRadius: 48,
    camera: 'none',
    material: 'aluminium',
    crown: true,
  },

  'apple-tv': {
    id: 'apple-tv',
    label: 'Apple TV',
    family: 'apple',
    chassis: 'tv',
    width: 1280,
    height: 720,
    bezel: 8,
    chromeAbove: 8,
    chromeBelow: 96,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 6,
    camera: 'none',
    material: 'graphite',
    speakers: true,
  },

  /* ----------------------------------------------------------- android -- */

  'pixel-pro': {
    id: 'pixel-pro',
    label: 'Pixel Pro',
    family: 'android',
    chassis: 'phone',
    width: 412,
    height: 892,
    bezel: 9,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 40,
    chassisRadius: 48,
    camera: 'punch-hole',
    sideButtons: true,
    homeIndicator: true,
    cameraBump: true,
  },

  pixel: {
    id: 'pixel',
    label: 'Pixel',
    family: 'android',
    chassis: 'phone',
    width: 412,
    height: 870,
    bezel: 9,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 36,
    chassisRadius: 44,
    camera: 'punch-hole',
    sideButtons: true,
    homeIndicator: true,
  },

  'pixel-fold': {
    id: 'pixel-fold',
    label: 'Pixel Fold',
    family: 'android',
    chassis: 'tablet',
    // Unfolded: a small, nearly square tablet rather than a phone.
    width: 842,
    height: 800,
    bezel: 9,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 12,
    chassisRadius: 20,
    camera: 'punch-hole',
    foldSeam: true,
  },

  'galaxy-ultra': {
    id: 'galaxy-ultra',
    label: 'Galaxy Ultra',
    family: 'android',
    chassis: 'phone',
    width: 412,
    height: 915,
    bezel: 7,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    // Squarer than the Pixel, which is most of what separates them on sight.
    screenRadius: 20,
    chassisRadius: 26,
    camera: 'punch-hole',
    material: 'titanium',
    sideButtons: true,
    homeIndicator: true,
    cameraBump: true,
  },

  galaxy: {
    id: 'galaxy',
    label: 'Galaxy',
    family: 'android',
    chassis: 'phone',
    width: 384,
    height: 854,
    bezel: 8,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 34,
    chassisRadius: 42,
    camera: 'punch-hole',
    sideButtons: true,
    homeIndicator: true,
  },

  'galaxy-fold': {
    id: 'galaxy-fold',
    label: 'Galaxy Z Fold',
    family: 'android',
    chassis: 'tablet',
    width: 904,
    height: 830,
    bezel: 8,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 10,
    chassisRadius: 18,
    camera: 'punch-hole',
    foldSeam: true,
  },

  oneplus: {
    id: 'oneplus',
    label: 'OnePlus',
    family: 'android',
    chassis: 'phone',
    width: 412,
    height: 919,
    bezel: 8,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 38,
    chassisRadius: 46,
    camera: 'punch-hole',
    sideButtons: true,
    homeIndicator: true,
    cameraBump: true,
  },

  xiaomi: {
    id: 'xiaomi',
    label: 'Xiaomi',
    family: 'android',
    chassis: 'phone',
    width: 393,
    height: 873,
    bezel: 8,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 36,
    chassisRadius: 44,
    camera: 'punch-hole',
    sideButtons: true,
    homeIndicator: true,
  },

  'galaxy-tab': {
    id: 'galaxy-tab',
    label: 'Galaxy Tab',
    family: 'android',
    chassis: 'tablet',
    width: 800,
    height: 1280,
    bezel: 10,
    chromeAbove: 12,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 12,
    chassisRadius: 20,
    camera: 'dot',
  },

  'wear-os': {
    id: 'wear-os',
    label: 'Wear OS watch',
    family: 'android',
    chassis: 'watch',
    // Round, so the viewport is square and the chassis radius makes the circle.
    width: 227,
    height: 227,
    bezel: 14,
    chromeAbove: 0,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 999,
    chassisRadius: 999,
    camera: 'none',
    material: 'graphite',
    crown: true,
  },

  /* ----------------------------------------------------------- windows -- */

  'surface-laptop': {
    id: 'surface-laptop',
    label: 'Surface Laptop',
    family: 'windows',
    chassis: 'laptop',
    width: 1152,
    height: 768,
    bezel: 14,
    chromeAbove: 16,
    chromeBelow: 16,
    overhang: 20,
    screenRadius: 2,
    chassisRadius: 8,
    camera: 'dot',
    material: 'aluminium',
    speakers: true,
  },

  'windows-laptop-13': {
    id: 'windows-laptop-13',
    label: 'Laptop 13"',
    family: 'windows',
    chassis: 'laptop',
    width: 1280,
    height: 800,
    bezel: 12,
    chromeAbove: 14,
    chromeBelow: 15,
    overhang: 22,
    screenRadius: 2,
    chassisRadius: 8,
    camera: 'dot',
    material: 'graphite',
    speakers: true,
  },

  'surface-pro': {
    id: 'surface-pro',
    label: 'Surface Pro',
    family: 'windows',
    chassis: 'tablet',
    width: 912,
    height: 1368,
    bezel: 14,
    chromeAbove: 14,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 6,
    chassisRadius: 12,
    camera: 'dot',
  },

  'desktop-monitor': {
    id: 'desktop-monitor',
    label: 'Monitor',
    family: 'windows',
    chassis: 'monitor',
    width: 1440,
    height: 810,
    bezel: 10,
    chromeAbove: 10,
    chromeBelow: 120,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 8,
    camera: 'none',
    material: 'graphite',
  },

  'monitor-4k': {
    id: 'monitor-4k',
    label: 'Monitor 4K',
    family: 'windows',
    chassis: 'monitor',
    width: 1920,
    height: 1080,
    bezel: 9,
    chromeAbove: 9,
    chromeBelow: 130,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 8,
    camera: 'none',
    material: 'graphite',
  },

  ultrawide: {
    id: 'ultrawide',
    label: 'Ultrawide 21:9',
    family: 'windows',
    chassis: 'monitor',
    width: 1720,
    height: 720,
    bezel: 9,
    chromeAbove: 9,
    chromeBelow: 120,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 8,
    camera: 'none',
    material: 'graphite',
  },

  /* ----------------------------------------------------------- generic -- */

  browser: {
    id: 'browser',
    label: 'Browser',
    family: 'generic',
    chassis: 'browser',
    width: 1280,
    height: 800,
    bezel: 0,
    // The tab strip and address bar.
    chromeAbove: 72,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 0,
    chassisRadius: 10,
    camera: 'none',
    browserChrome: 'mac',
  },

  'browser-windows': {
    id: 'browser-windows',
    label: 'Browser (Windows)',
    family: 'generic',
    chassis: 'browser',
    width: 1366,
    height: 768,
    bezel: 0,
    chromeAbove: 72,
    chromeBelow: 0,
    overhang: 0,
    screenRadius: 0,
    // Windows draws square window corners.
    chassisRadius: 2,
    camera: 'none',
    browserChrome: 'windows',
  },

  tv: {
    id: 'tv',
    label: 'TV',
    family: 'generic',
    chassis: 'tv',
    width: 1920,
    height: 1080,
    bezel: 10,
    chromeAbove: 10,
    chromeBelow: 110,
    overhang: 0,
    screenRadius: 2,
    chassisRadius: 6,
    camera: 'none',
    material: 'graphite',
    speakers: true,
  },
} as const satisfies Record<string, DeviceSpec>;

export type DeviceId = keyof typeof DEVICES;

/** Every device id, in picker order. */
export const DEVICE_IDS = Object.keys(DEVICES) as DeviceId[];

export function getDevice(id: DeviceId): DeviceSpec {
  return DEVICES[id];
}

/** The devices in one family, for a grouped picker. */
export function devicesInFamily(family: DeviceSpec['family']): DeviceSpec[] {
  return DEVICE_IDS.map((id) => DEVICES[id]).filter((spec) => spec.family === family);
}
